packages:
  - packages/*
  - examples/*

ignoredBuiltDependencies:
  - faiss-node
  - '@pinecone-database/pinecone'
  - weaviate-ts-client
  - chromadb
  - pg

linkWorkspacePackages: true

onlyBuiltDependencies:
  - tree-sitter-cli

recursiveInstall: false

sharedWorkspaceLockfile: true
